.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Models/ErrorViewModel.cs
namespace FlightSearchEngine.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Models/FlightHotelResult.cs
namespace FlightSearchEngine.Models
{
    public class FlightHotelResult
    {
        public int FlightId { get; set; }
        public string FlightName { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public string HotelName { get; set; }
        public decimal TotalCost { get; set; }
    }
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Models/FlightResult.cs
namespace FlightSearchEngine.Models
{
    public class FlightResult
    {
        public int FlightId { get; set; }
        public string FlightName { get; set; }
        public string FlightType { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public decimal TotalCost { get; set; }
    }
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Models/SearchViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace FlightSearchEngine.Models
{
    public class SearchViewModel
    {
        //[Required]
        public string Source { get; set; }
        //[Required]
        public string Destination { get; set; }
        [Required]
        [Range(1, 10)]
        public int NumberOfPersons { get; set; }

        public SelectList? SourceList { get; set; }
        public SelectList? DestinationList { get; set; }
    }
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Controllers/FlightController.cs
using FlightSearchEngine.Data;
using FlightSearchEngine.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FlightSearchEngine.Controllers
{
    public class FlightController : Controller
    {
        private readonly DatabaseHelper _db;

        public FlightController(IConfiguration configuration)
        {
            _db = new DatabaseHelper(configuration);
        }

        public async Task<IActionResult> Index()
        {
            var model = new SearchViewModel();

            var sources = await _db.GetSourcesAsync();
            var destinations = await _db.GetDestinationsAsync();

            model.SourceList = new SelectList(sources,model.Source);
            model.DestinationList = new SelectList(destinations,model.Destination);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> SearchFlights(SearchViewModel model)
        {
            if (!ModelState.IsValid)
            {

                model.SourceList = new SelectList(await _db.GetSourcesAsync());
                model.DestinationList = new SelectList(await _db.GetDestinationsAsync());
                return View("Index", model);
            }
            var results = await _db.SearchFlightsAsync(model.Source, model.Destination, model.NumberOfPersons);

            return View("Results", results);
        }


        [HttpPost]
        public async Task<IActionResult> SearchFlightsWithHotels(SearchViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.SourceList = new SelectList(await _db.GetSourcesAsync());
                model.DestinationList = new SelectList(await _db.GetDestinationsAsync());
                return View("Index", model);
            }
            var results = await _db.SearchFlightsWithHotelsAsync(model.Source, model.Destination, model.NumberOfPersons);

            return View("FlightHotelResult", results);
        }
    }
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Controllers/HomeController.cs
using System.Diagnostics;
using FlightSearchEngine.Models;
using Microsoft.AspNetCore.Mvc;

namespace FlightSearchEngine.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Views/Flight/FlightHotelResult.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<FlightSearchEngine.Models.FlightHotelResult>
@if (Model == null || !Model.Any())
{
    <p>No results found.</p>
}
else
{
    <table border="1">
        <tr>
            <th>FlightId</th>
            <th>FlightName</th>
            <th>Source</th>
            <th>Destination</th>
            <th>TotalCost</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FlightId</td>
                <td>@item.FlightName</td>
                <td>@item.Source</td>
                <td>@item.Destination</td>
                <td>@item.TotalCost</td>
            </tr>
        }
    </table>
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Views/Flight/Index.cshtml
@model FlightSearchEngine.Models.SearchViewModel

<form asp-asp-controller="Flight" asp-action="SearchFlights" method="post">
    <div>
        <label>Source</label>
        <select asp-for="Source" asp-items="Model.SourceList">
            <option value="">-- Select Source --</option>
        </select>

    </div>

    <div>
        <label>Destination</label>
        <select asp-for="Destination" asp-items="Model.DestinationList">
            <option value="">-- Select Destination --</option>
        </select>
    </div>

    <div>
        <label>Number of Persons</label>
        <input asp-for="NumberOfPersons" type="number" />
    </div>

    <span asp-validation-summary="All"></span>

    <button formaction="@Url.Action("SearchFlights")">
        Search Flights Only
    </button>

    <button formaction="@Url.Action("SearchFlightsWithHotels")">
        Search Flight + Hotel
    </button>
</form>

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Views/Flight/Results.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<FlightSearchEngine.Models.FlightResult>
@if (Model == null || !Model.Any())
{
    <p>No results found.</p>
}
else
{
    <table border="1">
        <tr>
            <th>FlightId</th>
            <th>FlightName</th>
            <th>Source</th>
            <th>Destination</th>
            <th>TotalCost</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>@item.FlightId</td>
                <td>@item.FlightName</td>
                <td>@item.Source</td>
                <td>@item.Destination</td>
                <td>@item.TotalCost</td>
            </tr>
        }
    </table>
}

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

.NET Training/Assessments/28Feb2026/FlightSearchEngineProject/FlightSearchEngine/FlightSearchEngine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FlightSearchEngine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FlightSearchEngine.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FlightSearchEngine</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - FlightSearchEngine - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>